theme: minima

minima:
  social_links:
    - { platform: github,         user_url: "https://github.com/NivekNey" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=YnP8rS4AAAAJ&hl=en" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/kevinyen91" }
